# Site settings
title: Portfolio
description: Caleb's portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Caleb Stout
user_description: Hello, my name is Caleb, I am an up and coming full stack python developer. I went to University of California, Santa Cruz to become a UX Researcher and designer; instead I came out Problem Solver after taking a few courses in python with UX skills through both Udemy and Google.
user_title: Problem Solver
email: hisurfingc@yahoo.com
twitter_username: https://twitter.com/norsie3
github_username: https://github.com/Nors1e

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
